@baseUrl = http://localhost:3000/api/v1

### Buscar eventos
GET {{baseUrl}}/catalog/events?city=Madrid&artist=ArtistName
Content-Type: application/json

### Listar sedes (venues)
GET {{baseUrl}}/catalog/venues
Content-Type: application/json

### Búsqueda general
GET {{baseUrl}}/catalog/search
Content-Type: application/json
