@baseUrl = http://localhost:3000/api/v1

### Registro de usuario
POST {{baseUrl}}/identity/register
Content-Type: application/json

{
  "email": "user@example.com",
  "name": "User Name",
  "password": "password123"
}

### Login de usuario
# @name login
POST {{baseUrl}}/identity/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### Obtener perfil de usuario
GET {{baseUrl}}/identity/profile
Authorization: Bearer {{login.response.body.token}}
Content-Type: application/json
