@baseUrl = http://localhost:3000/api/v1
@authToken = {{login.response.body.token}}

### Crear orden
POST {{baseUrl}}/ordering/orders
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "id": "order-123",
  "userId": "user-456",
  "eventId": "event-789",
  "amount": 100
}

### Listar tickets
GET {{baseUrl}}/ordering/tickets
Authorization: Bearer {{authToken}}
Content-Type: application/json
